# Paquetes y Librerías

In [ ]:
!python --version

In [1]:
import numpy
numpy.version.version

'1.26.4'

In [2]:
import matplotlib
matplotlib.__version__

'3.7.5'

# Una Neurona Individual

In [3]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

In [4]:
output = (inputs[0]*weights[0] +
 inputs[1]*weights[1] +
 inputs[2]*weights[2] + bias)
print(output)

2.3


In [5]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

In [6]:
output = (inputs[0]*weights[0] +
 inputs[1]*weights[1] +
 inputs[2]*weights[2] +
 inputs[3]*weights[3] + bias)
print(output)

4.8


# Una Capa de Neuronas

In [7]:
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5
outputs = [
 # Neurona 1:
 inputs[0]*weights1[0] +
 inputs[1]*weights1[1] +
 inputs[2]*weights1[2] +
 inputs[3]*weights1[3] + bias1,
 # Neurona 2:
 inputs[0]*weights2[0] +
 inputs[1]*weights2[1] +
 inputs[2]*weights2[2] +
 inputs[3]*weights2[3] + bias2,
 # Neurona 3:
 inputs[0]*weights3[0] +
 inputs[1]*weights3[1] +
 inputs[2]*weights3[2] +
 inputs[3]*weights3[3] + bias3]
print(outputs)

[4.8, 1.21, 2.385]


In [8]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]
# Salidad de la capa actual
layer_outputs = []
# Para cada neurona
for neuron_weights, neuron_bias in zip(weights, biases):
 # Salida anulada de la neurona dada
 neuron_output = 0
 # Para cada entrada y peso hacia la neurona
 for n_input, weight in zip(inputs, neuron_weights):
     # Multiplica esta entrada por el peso asociado
     # y agrégalo a la variable de salida de la neurona
     neuron_output += n_input*weight
 # Agrega el sesgo
 neuron_output += neuron_bias
 # Coloca el resultado de la neurona en la lista de salida de la capa
 layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


# Tensores, Arreglos y Vectores

## Tensores

In [9]:
l = [1,5,6,2]

In [10]:
lol = [[1,5,6,2],
 [3,2,1,3]]

In [11]:
another_list_of_lists = [[4,2,3],
 [5,1]]

In [12]:
list_matrix_array = [[4,2],
 [5,1],
 [8,2]]

# Producto Punto y Adición de Vectores

In [13]:
a = [1, 2, 3]
b = [2, 3, 4]
dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)

20


In [14]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


# Una Capa de Neuronas con NumPy

In [15]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


# Un Lote de Datos

In [16]:
inputs = [[1, 2, 3, 2.5], [2, 5, -1, 2], [-1.5, 2.7, 3.3, -0.8]]

# Producto Matricial

# Transposición para el Producto Matricial

In [17]:
import numpy as np
np.array([[1, 2, 3]])

array([[1, 2, 3]])

In [18]:
a = [1, 2, 3]
print(np.array([a]))

[[1 2 3]]


In [19]:
a = [1, 2, 3]
print(np.expand_dims(np.array(a), axis=0))

[[1 2 3]]


In [20]:
import numpy as np
a = [1, 2, 3]
b = [2, 3, 4]
a = np.array([a])
b = np.array([b]).T
print(np.dot(a, b))

[[20]]


In [21]:
import numpy as np
inputs = [[1.0, 2.0, 3.0, 2.5],
 [2.0, 5.0, -1.0, 2.0],
 [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]
layer_outputs = np.dot(inputs, np.array(weights).T) + biases
print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
