##Perceptrón Multicapa sin Librerías

In [ ]:
import numpy as np

# Función de activación sigmoide
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivada de la función sigmoide
def sigmoid_derivada(x):
    return x * (1 - x)

# Datos de entrada (4 ejemplos con 2 características cada uno)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Salida esperada (operación AND)
y = np.array([[0], [1], [1], [0]])

# Inicialización aleatoria de pesos
np.random.seed(42)
pesos_entrada_oculta = np.random.rand(2, 2)  # 2 neuronas de entrada, 2 en la capa oculta
pesos_oculta_salida = np.random.rand(2, 1)  # 2 neuronas en la capa oculta, 1 en la capa de salida

# Parámetros
tasa_aprendizaje = 0.1
epocas = 100

# Entrenamiento
for epoch in range(epocas):
    # Propagación hacia adelante
    capa_oculta = sigmoid(np.dot(X, pesos_entrada_oculta))
    salida = sigmoid(np.dot(capa_oculta, pesos_oculta_salida))

    # Cálculo del error
    error = y - salida

    # Retropropagación del error
    delta_salida = error * sigmoid_derivada(salida)
    delta_oculta = delta_salida.dot(pesos_oculta_salida.T) * sigmoid_derivada(capa_oculta)

    # Actualización de los pesos
    pesos_oculta_salida += capa_oculta.T.dot(delta_salida) * tasa_aprendizaje
    pesos_entrada_oculta += X.T.dot(delta_oculta) * tasa_aprendizaje

# Mostrar resultados
print("Salida después del entrenamiento:")
print(salida)

Salida después del entrenamiento:
[[0.50817496]
 [0.51073366]
 [0.51108049]
 [0.51309019]]


##Perceptrón Multicapa con Librerías

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Definición del modelo
modelo = Sequential()

# Capa de entrada explícita
modelo.add(Input(shape=(2,)))  # Input de 2 características

# Capa oculta con 2 neuronas y activación sigmoide
modelo.add(Dense(2, activation='sigmoid'))

# Capa de salida con 1 neurona (clasificación binaria)
modelo.add(Dense(1, activation='sigmoid'))

# Compilación del modelo
modelo.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Datos de entrada
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Salidas esperadas
y = np.array([[0], [1], [1], [0]])

# Entrenamiento del modelo
modelo.fit(X, y, epochs=100, verbose=0)

# Evaluación
predicciones = modelo.predict(X)
print("Predicciones:")
print(predicciones)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
Predicciones:
[[0.58262664]
 [0.52239925]
 [0.5462057 ]
 [0.4994327 ]]


##Perceptrón Multicapa sklearn

In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier

# Datos de entrada
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Salidas esperadas
y = np.array([0, 1, 1, 0])  # Debe ser un vector unidimensional para MLPClassifier

# Definición del modelo
modelo = MLPClassifier(hidden_layer_sizes=(2,), activation='logistic', max_iter=100)

# Entrenamiento del modelo
modelo.fit(X, y)

# Evaluación
predicciones = modelo.predict(X)
print("Predicciones:")
print(predicciones)

Predicciones:
[0 0 0 0]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
